- block:
  - name: Download Deno installer script
    get_url:
      url: https://deno.land/install.sh
      dest: "{{ temp_dir }}/install-deno.sh"
      mode: '+x'

  - name: Run Deno installer script
    command: "{{ temp_dir }}/install-deno.sh"
    args:
      creates: "{{ home_dir }}/.deno/bin/deno"

  - name: Remove Deno installer script
    ansible.builtin.file:
      path: "{{ temp_dir }}/install-deno.sh"
      state: absent

  tags:
    - install
    - install-deno
    - update
    - update-deno
