- block:
  - name: Check if google cloud sdk repository has been added
    lineinfile:
      path: "/etc/apt/sources.list.d/google-cloud-sdk.list"
      line: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main"
      create: yes
    become: true

  - name: Add Google Cloud apt key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      keyring: /usr/share/keyrings/cloud.google.gpg
      state: present
    become: true

  - name: Update packages and install Google Cloud SDK and auth plugin
    apt:
      name:
        - google-cloud-sdk
        - google-cloud-sdk-gke-gcloud-auth-plugin
      update_cache: yes
      state: present
    become: true

  tags:
    - install
    - install-google-cloud
    - update
    - update-google-cloud
