- block:
  - name: Install i3 packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "i3"
      - "picom"
      - "polybar"
      - "rofi"
      - "feh"
      - "arandr"

  - name: Setup the i3 scaling files
    command: "./ubuntu"
    args:
      chdir: "{{ dotfiles_dir }}"
    environment:
      STOW_FOLDERS: "i3-scaling"
    tags:
      - install-i3-scaling
      - update-i3-scaling

  tags:
    - install
    - install-i3
    - update
    - update-i3
