- block:
  - name: Set kubectl version
    set_fact:
      kubectl_version: "1.28.6"

  - name: Download latest kubectl
    get_url:
      url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
      dest: "{{ user_bin }}/kubectl"
      mode: '0755'
      force: true
    become: true

  tags:
    - install
    - install-kubectl
    - update
    - update-kubectl
