- block:
  - name: Download Rancher desktop gpg key
    get_url:
      url: https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key
      dest: "{{ temp_dir }}/rancher-desktop.key"
      mode: '0644'

  - name: Convert GPG key to dearmored format
    ansible.builtin.command:
      cmd: gpg --dearmor -o /usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg {{ temp_dir }}/rancher-desktop.key
    become: true
    args:
      creates: /usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg

  - name: Add Rancher APT repository
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./"
      filename: isv-rancher-stable
      state: present
    become: true

  - name: Update rancher desktop packages
    apt:
      update_cache: true
    become: true

  - name: Setup the bin dotfiles
    command: "./ubuntu"
    args:
      chdir: "{{ dotfiles_dir }}"
    environment:
      STOW_FOLDERS: "rancher-desktop"
    tags:
      - update-rancher

  - name: Install Rancher desktop
    apt:
      name: "rancher-desktop"
    become: true
    tags:
      - update-rancher

  tags:
    - install-rancher
