#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## pull ansible
git clone https://github.com/coldb/ansible.git
cd ansible

## TODO: Remove before merge
git fetch
git switch u24-refactoring

if [ -n "$1" ]; then
    ansible-playbook local.yaml -t $1 --ask-become-pass --ask-vault-pass
else
    ansible-playbook local.yaml -t install --ask-become-pass --ask-vault-pass
fi
