- hosts: localhost
  pre_tasks:
    - name: Update cache
      become: true
      apt: 
        update_cache: true
      tags:
      - zsh
      - node
  tasks: 
  - import_tasks: tasks/zsh.yaml
  - import_tasks: tasks/node.yaml
  - import_tasks: tasks/dotfiles.yaml
