- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt: 
        update_cache: true
      tags:
      - zsh
      - node
  tasks: 
  - import_tasks: tasks/zsh.yaml
  - import_tasks: tasks/node.yaml
