- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ubuntu/setup.yaml
    - import_tasks: tasks/ubuntu/tools/_index.yaml
    - import_tasks: tasks/ubuntu/ssh.yaml
    - import_tasks: tasks/ubuntu/github.yaml
    - import_tasks: tasks/ubuntu/core.yaml
    - import_tasks: tasks/ubuntu/audio.yaml
    - import_tasks: tasks/ubuntu/video.yaml
    - import_tasks: tasks/ubuntu/shell/_index.yaml
    - import_tasks: tasks/ubuntu/terminals/_index.yaml
    - import_tasks: tasks/ubuntu/keyboard.yaml
    - import_tasks: tasks/ubuntu/fonts/_index.yaml
    - import_tasks: tasks/ubuntu/application/_index.yaml
    - import_tasks: tasks/ubuntu/work.yaml
    - import_tasks: tasks/ubuntu/personal.yaml
