- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    username: "coldb"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
      - rdp
  tasks: 
  - import_tasks: tasks/ssh.yaml
  - import_tasks: tasks/core.yaml
  - import_tasks: tasks/zsh.yaml
  - import_tasks: tasks/node.yaml
  - import_tasks: tasks/dotfiles.yaml
  - import_tasks: tasks/productivity-tools.yaml
  - import_tasks: tasks/keyboard.yaml
  - import_tasks: tasks/rdp.yaml
  - import_tasks: tasks/neovim.yaml
  - import_tasks: tasks/fonts.yaml
