#!/usr/bin/env bash

declare -A options=(
  ["debug"]=""
  ["install"]="--ask-vault-pass"
  ["install-audio"]=""
  ["install-brave"]=""
  ["install-browsers"]=""
  ["install-chrome"]=""
  ["install-core"]=""
  ["install-deno"]=""
  ["install-docker"]=""
  ["install-firefox"]=""
  ["install-fonts"]=""
  ["install-ghostty"]=""
  ["install-neovim"]=""
  ["install-neovim-latest"]=""
  ["install-node"]=""
  ["install-thunderbird"]=""
  ["install-video"]=""
  ["install-zsh"]=""
  ["install-i3"]=""
  ["update"]=""
  ["update-audio"]=""
  ["update-brave"]=""
  ["update-browsers"]=""
  ["update-chrome"]=""
  ["update-core"]=""
  ["update-deno"]=""
  ["update-docker"]=""
  ["update-firefox"]=""
  ["update-fonts"]=""
  ["update-ghostty"]=""
  ["update-neovim"]=""
  ["update-neovim-latest"]=""
  ["update-thunderbird"]=""
  ["update-video"]=""
  ["update-zsh"]=""
  ["update-i3"]=""
  ["bruno"]=""
  ["dotfiles"]="--ask-vault-pass"
  ["keyboard"]=""
  ["laptop"]=""
  ["lazygit"]=""
  ["node"]=""
  ["personal"]="--ask-vault-pass"
  ["productivity"]=""
  ["rdp"]=""
  ["slack"]=""
  ["ssh"]="--ask-vault-pass"
  ["work"]="--ask-vault-pass"
)

selected_tags=$(printf "%s\n" "${!options[@]}" | fzf --multi --prompt="Select tags: " --header="Use Tab to select multiple tags")

if [ -z "$selected_tags" ]; then
  echo "No tags selected. Exiting."
  exit 1
fi

tag_list=""
extra_flags="--ask-become-pass"

for tag in $selected_tags; do
  tag_list+="$tag,"
  for flag in ${options[$tag]}; do
    if [[ -n "$flag" && ! "$extra_flags" =~ $flag ]]; then
      extra_flags+=" $flag"
    fi
  done
done

tag_list=${tag_list%,}

ansible_command="ansible-playbook local.yaml --tags \"$tag_list\" $extra_flags"

echo "Executing: $ansible_command"
eval $ansible_command
