#!/usr/bin/env bash

declare -A options=(
  ["debug"]=""
  ["install"]="--ask-vault-pass"
  ["install-brave"]=""
  ["install-browsers"]=""
  ["install-chrome"]=""
  ["install-deno"]=""
  ["install-docker"]=""
  ["install-firefox"]=""
  ["install-fonts"]=""
  ["install-ghostty"]=""
  ["install-thunderbird"]=""
  ["update"]=""
  ["update-brave"]=""
  ["update-browsers"]=""
  ["update-chrome"]=""
  ["update-deno"]=""
  ["update-docker"]=""
  ["update-firefox"]=""
  ["update-fonts"]=""
  ["update-ghostty"]=""
  ["update-thunderbird"]=""
  ["browser-brave"]=""
  ["browser-brave-update"]=""
  ["browser-chrome"]=""
  ["browser-chrome-update"]=""
  ["browser-firefox"]=""
  ["browser-firefox-update"]=""
  ["browsers"]=""
  ["browsers-update"]=""
  ["bruno"]=""
  ["core"]=""
  ["deno"]=""
  ["docker"]=""
  ["dotfiles"]="--ask-vault-pass"
  ["email"]=""
  ["email-thunderbird"]=""
  ["email-thunderbird-update"]=""
  ["fonts"]=""
  ["i3-scaling"]=""
  ["i3wm"]=""
  ["keyboard"]=""
  ["laptop"]=""
  ["lazygit"]=""
  ["neovim"]=""
  ["neovim-latest"]=""
  ["node"]=""
  ["personal"]="--ask-vault-pass"
  ["productivity"]=""
  ["rdp"]=""
  ["slack"]=""
  ["ssh"]="--ask-vault-pass"
  ["work"]="--ask-vault-pass"
  ["zsh"]=""
)

selected_tags=$(printf "%s\n" "${!options[@]}" | fzf --multi --prompt="Select tags: " --header="Use Tab to select multiple tags")

if [ -z "$selected_tags" ]; then
  echo "No tags selected. Exiting."
  exit 1
fi

tag_list=""
extra_flags="--ask-become-pass"

for tag in $selected_tags; do
  tag_list+="$tag,"
  for flag in ${options[$tag]}; do
    if [[ -n "$flag" && ! "$extra_flags" =~ $flag ]]; then
      extra_flags+=" $flag"
    fi
  done
done

tag_list=${tag_list%,}

ansible_command="ansible-playbook local.yaml --tags \"$tag_list\" $extra_flags"

echo "Executing: $ansible_command"
eval $ansible_command
