- block:
  - name: Install System Packages
    become: true
    apt:
      name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]

  - name: Install Utilities
    become: true
    apt:
      name: [ "curl", "unzip", "htop", "lsof", "gettext", "python3-pip", "dconf-editor", "moreutils", "lua5.1"]

  - name: Install Audio control (pavucontrol)
    become: true
    apt:
      name: "pavucontrol"

  - name: Check if lspci command is available
    command: which lspci
    register: lspci_check
    ignore_errors: true

  - name: Install tooling for nvidia check
    become: true
    apt:
      name: "pciutils"
    when: lspci_check.rc != 0

  - name: Check if NVIDIA hardware is present
    ansible.builtin.shell: "lspci | grep -i nvidia"
    register: nvidia_check
    ignore_errors: true

  - name: Install nvidia-settings if NVIDIA hardware is found
    ansible.builtin.package:
      name: "nvidia-settings"
      state: present
    when: nvidia_check.rc == 0

  - name: Get latest playerctl version from GitHub API
    shell: "curl -s 'https://api.github.com/repos/altdesktop/playerctl/releases/latest' | grep -Po '\"tag_name\": \"v\\K[^\"]*'"
    register: playerctl_version

  - name: Download latest playerctl
    ansible.builtin.get_url:
      url: "https://github.com/altdesktop/playerctl/releases/download/v{{ playerctl_version.stdout }}/playerctl-{{ playerctl_version.stdout }}_amd64.deb"
      dest: "{{ temp_dir }}/playerctl.deb"

  - name: Install playerctl
    become: true
    ansible.builtin.apt:
      deb: "{{ temp_dir }}/playerctl.deb"

  - name: Remove playerctl install file
    ansible.builtin.file:
      path: "{{ temp_dir }}/playerctl.deb"
      state: absent

  tags:
    - install
    - core
