- block:
  - name: Install Core packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "build-essential"
      - "cmake"
      - "pkg-config"
      - "libpthread-stubs0-dev"
      - "python3-pip"
      - "dconf-editor"
      - "moreutils"
      - "lua5.1"

  - name: Install productivity packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "unzip"
      - "wireshark"
      - "fzf"
      - "gimp"
      - "xclip"
      - "tldr"
      - "ripgrep"
      - "ksnip"
      - "bat"
      - "curl"
      - "htop"
      - "lsof"
      - "gettext"

  tags:
    - testing
    - install
    - install-core
    - update
    - update-core
