- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "compton", "curl", "htop", "lsof", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils" ]
  tags:
    - install
    - core

- name: Install System Packages 4 (i3)
  become: true
  apt:
    name: "i3"
  tags:
    - install
    - core

- name: Install System Packages 5 (docker.io)
  become: true
  apt:
    name: ["docker.io", "docker-compose-plugin"]
  tags:
    - install
    - core

- name: Add permissions for docker command
  shell: "usermod -aG docker {{ username }}"
  become: true
  tags:
    - install
    - core

# Playerctl is used to enable the play, pause, next, prev media keys
- name: Download playerctl for media controls
  ansible.builtin.get_url:
    url: https://github.com/altdesktop/playerctl/releases/download/v2.4.1/playerctl-2.4.1_amd64.deb
    dest: "{{ lookup('env', 'HOME') }}/playerctl-2.4.1_amd64.deb"
  tags:
    - install
    - core

- name: Install playerctl
  become: true
  ansible.builtin.apt:
    deb: "{{ lookup('env', 'HOME') }}/playerctl-2.4.1_amd64.deb"
  tags:
    - install
    - core

- name: Remove playerctl install file
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/playerctl-2.4.1_amd64.deb"
    state: absent
  tags:
    - install
    - core

- name: Install picom i3 compositor
  become: true
  apt:
    name: "picom"
  tags:
    - install
    - core

- name: Install polybar for i3
  become: true
  apt:
    name: "polybar"
  tags:
    - install
    - core

- name: Install rofi to replace dmenu in i3
  become: true
  apt:
    name: "rofi"
  tags:
    - install
    - core

- name: Install feh for backgrounds in i3
  become: true
  apt:
    name: "feh"
  tags:
    - install
    - core

- name: Install arandr
  become: true
  apt:
    name: "arandr"
  tags:
    - install
    - core

