- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "compton", "curl", "htop", "lsof", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "ubuntu-mate-desktop" ]
  tags:
    - install
    - core

- name: Install System Packages 4 (i3)
  become: true
  apt:
    name: "i3"
  tags:
    - install
    - core

- name: Check if X11 $DISPLAY variable is set
  ansible.builtin.set_fact:
    display_set: "{{ ansible_env.DISPLAY is defined and ansible_env.DISPLAY != '' }}"

- name: dconf i3 - Set window manager to 'i3'
  ansible.builtin.shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  when: display_set
  tags:
    - install
    - core

- name: dconf i3 - Disable show desktop icons
  ansible.builtin.shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  when: display_set
  tags:
    - install
    - core

# - name: dconf i3
#   shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
#   tags:
#     - install
#     - core

# - name: dconf i3
#   shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
#   tags:
#     - install
#     - core