- block:
  - name: Install Core packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "build-essential"
      - "cmake"
      - "pkg-config"
      - "libpthread-stubs0-dev"
      - "python3-pip"
      - "dconf-editor"
      - "moreutils"
      - "lua5.1"

  tags:
    - install
    - install-core
    - update
    - update-core
