- block:
  - name: Download Deno installer script
    get_url:
      url: https://deno.land/install.sh
      dest: "{{ temp_dir }}/install-deno.sh"
      mode: '+x'

  - name: Run Deno installer script
    command: "{{ temp_dir }}/install-deno.sh"
    args:
      creates: "{{ home_dir }}/.deno/bin/deno"

  tags:
    - deno
    - install
