- block:
  - name: Installing stow
    apt:
      name: [ "stow" ]
    become: true
    tags:
      - keyboard

  - name: Cloning .dotfiles
    ansible.builtin.git:
      repo: 'git@github.com:coldb/.dotfiles.git' 
      dest: "{{ home_dir }}/.dotfiles"
      recursive: true
      update: true
      accept_hostkey: true
      version: u24-refactor
    tags:
      - keyboard

  - name: Stow dotfiles
    shell: cd {{ home_dir }}/.dotfiles && ./ubuntu
    tags:
      - keyboard

  - name: Include variables
    include_vars: auth_codes/variables.yaml

  - name: Set .dotfiles user.name local configuration
    community.general.git_config:
      name: user.name
      repo: "{{ home_dir }}/.dotfiles"
      scope: local
      value: "{{ git_user }}"

  - name: Set .dotfiles user.email local configuration
    community.general.git_config:
      name: user.email
      repo: "{{ home_dir }}/.dotfiles"
      scope: local
      value: "{{ git_email }}"

  # - name: Enable high resolution monitor support
  #   shell: cd {{ home_dir }}/.dotfiles && ./ubuntu 
  #   environment:
  #     STOW_FOLDERS: "i3-scaling"
  #   tags:
  #     - i3-scaling

  tags:
    - install
    - dotfiles
