- name: Upgrade Thunderbird to the latest version
  command: "flatpak update org.mozilla.Thunderbird"
  when: docker_container == False
  tags:
    - browser-thunderbird-update

- block:
  - name: Install Thunderbird via Flatpak
    command: "flatpak install -y flathub org.mozilla.Thunderbird"
    when: docker_container == False
    tags:
      - email-thunderbird-install

  - name: Create a symbolic link for Thunderbird
    ansible.builtin.file:
      src: /var/lib/flatpak/exports/bin/org.mozilla.Thunderbird
      dest: /usr/bin/org.mozilla.Thunderbird
    when: docker_container == False
    become: true

  tags:
    - install
    - email
