- name: Download latest Nerd Font CascadiaMono appimage
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip
    dest: ~/CascadiaMono.zip
  tags:
    - install
    - fonts

- name: Unzip Nerd Font zip file
  shell: unzip ~/CascadiaMono.zip -d ~/.fonts
  tags:
    - install
    - fonts

- name: Update fonts cache to add the new font
  shell: fc-cache -fv
  tags:
    - install
    - fonts

- name: Remove downloaded font zip file
  ansible.builtin.file:
    path: ~/CascadiaMono.zip
    state: absent
  tags:
    - install
    - fonts
