- name: Create tools directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/tools"
    state: directory
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard
    
- name: Download kanata_wintercept.exe from Git releases
  get_url:
    url: "https://github.com/jtroo/kanata/releases/download/v1.5.0/kanata"
    dest: "{{ lookup('env', 'HOME') }}/tools/kanata"
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard

# https://github.com/jtroo/kanata/blob/main/docs/setup-linux.md

- name: Make sure uinput group exists
  ansible.builtin.group:
    name: uinput
    state: present
  become: true
  tags:
    - install
    - dotfiles
    - keyboard

- name: Add the user to input and uinput groups
  ansible.builtin.user:
    name: "{{ username }}"
    groups: input,uinput
    append: true
  become: true
  tags:
    - install
    - dotfiles
    - keyboard

- name: Add udev rule for uinput group
  ansible.builtin.copy:
    content: 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"'
    dest: /etc/udev/rules.d/99-input.rules
  become: true
  tags:
    - install
    - dotfiles
    - keyboard
    
- name: Reload udev and apply rules
  shell: udevadm control --reload-rules && udevadm trigger 
  become: true
  tags:
    - install
    - dotfiles
    - keyboard

- name: Get information about /dev/uinput
  ansible.builtin.stat:
    path: /dev/uinput
  register: uinput_stats
  tags:
    - install
    - dotfiles
    - keyboard

- name: Verify /dev/uinput settings
  ansible.builtin.assert:
    that:
      - uinput_stats.stat.exists
      - uinput_stats.stat.mode == '0660'
      - uinput_stats.stat.pw_name == 'root'
      - uinput_stats.stat.gr_name == 'uinput'
    fail_msg: "/dev/uinput does not have the correct permissions"
    success_msg: "/dev/uinput permissions are correct"
  tags:
    - install
    - dotfiles
    - keyboard

- name: Load the uinput module into the kernel
  shell: modprobe uinput
  become: true
  tags:
    - install
    - dotfiles
    - keyboard

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable kanata systemd service and start it
  ansible.builtin.systemd_service:
    name: kanata
    state: started
    enabled: true