- name: Create tools directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/tools"
    state: directory
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard
    
- name: Download kanata_wintercept.exe from Git releases
  get_url:
    url: "https://github.com/jtroo/kanata/releases/download/v1.5.0/kanata"
    dest: "{{ lookup('env', 'HOME') }}/tools/kanata"
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: coldb
    group: uinput
  tags:
    - install
    - dotfiles
    - keyboard

# https://github.com/jtroo/kanata/blob/main/docs/setup-linux.md

- name: Make sure uinput group exists
  ansible.builtin.group:
    name: uinput
    state: present
  become: true
  tags:
    - install
    - dotfiles
    - keyboard

- name: Add the user to input and uinput groups
  ansible.builtin.user:
    name: coldb
    groups: input,uinput
    append: true
  become: true
  tags:
    - install
    - dotfiles
    - keyboard
