- name: Create tools directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/tools"
    state: directory
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard
    
- name: Download kanata_wintercept.exe from Git releases
  get_url:
    url: "https://github.com/jtroo/kanata/releases/download/v1.5.0/kanata"
    dest: "{{ lookup('env', 'HOME') }}/tools/kanata"
    mode: '0755'
  tags:
    - install
    - dotfiles
    - keyboard