- block:
  - name: Get the latest playerctl version from GitHub
    get_latest_git_release:
      repo_slug: "jtroo/kanata"
    register: kanata

  - name: Download latest kanata from Git releases
    get_url:
      url: "https://github.com/jtroo/kanata/releases/download/v{{ kanata.latest_version }}/kanata"
      dest: "/usr/bin/kanata"
      mode: '0755'
    become: true

  - name: Create the /etc/kanata directory
    file:
      path: /etc/kanata
      state: directory
      mode: '0755'
    become: true

  - name: Create link for the Kanata configuration file
    ansible.builtin.file:
      src: "{{ home_dir }}/.dotfiles/keyboard/kanata/eng-us.kbd"
      dest: /etc/kanata/eng-us.kbd
      state: link
    become: true

  - name: Create link for Kanata systemd service file
    ansible.builtin.file:
      src: "{{ home_dir }}/.dotfiles/keyboard/kanata.service"
      dest: /lib/systemd/system/kanata.service
      state: link
    become: true

  - name: Reload systemd to apply Kanata new service file
    systemd:
      daemon_reload: yes
    become: true

  - name: Start the Kanata service
    systemd:
      name: kanata
      state: started
    become: true

  - name: Enable the Kanata service to start at boot
    systemd:
      name: kanata
      enabled: yes
    become: true

  tags:
    - install
    - install-keyboard
    - update
    - update-keyboard
