- block:
  - name: Download kanata_wintercept.exe from Git releases
    get_url:
      url: "https://github.com/jtroo/kanata/releases/download/v1.5.0/kanata"
      dest: "/usr/bin/kanata"
      mode: '0755'
    become: true

  - name: Create the /etc/kanata directory
    file:
      path: /etc/kanata
      state: directory
      mode: '0755'
    become: true

  - name: Copy the Kanata configuration file to /etc/kanata/kanata.kbd
    copy:
      src: "{{ home_dir }}/.dotfiles/keyboard/kanata/eng-us.kbd"
      dest: /etc/kanata/eng-us.kbd
      mode: '0644'
    become: true

  - name: Install the Kanata systemd service file
    copy:
      src: "{{ home_dir }}/.dotfiles/keyboard/kanata.service"
      dest: /lib/systemd/system/kanata.service
      mode: '0644'
    become: true

  - name: Reload systemd to apply Kanata new service file
    systemd:
      daemon_reload: yes
    become: true

  - name: Start the Kanata service
    systemd:
      name: kanata
      state: started
    become: true

  - name: Enable the Kanata service to start at boot
    systemd:
      name: kanata
      enabled: yes
    become: true

  tags:
    - install
    - dotfiles
    - keyboard
