- name: Get the latest neovim version from GitHub
  get_latest_git_release:
    repo_slug: "neovim/neovim"
  register: neovim
  tags:
    - install
    - neovim
    - neovim-latest

- name: Set neovim to latest version
  set_fact:
    neovim_version: "{{ neovim.latest_version }}"
  tags: [never, neovim-latest ]

- block:
  - name: Install Fuse
    become: true
    apt:
      name: ["libfuse2t64"]
    tags:
      - neovim-latest

  - name: Set neovim version to local stable
    set_fact:
      neovim_version: 0.10.1

  - name: Download neovim appimage
    ansible.builtin.get_url:
      url: https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage
      dest: "{{ temp_dir }}/nvim.appimage"
    tags:
      - neovim-latest

  - name: Download latest neovim appimage checksum
    ansible.builtin.get_url:
      url: https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage.sha256sum
      dest: "{{ temp_dir }}/nvim.appimage.sha256sum"
    tags:
      - neovim-latest

  - name: Read the expected neovim checksum from the file
    shell: "cat {{ temp_dir }}/nvim.appimage.sha256sum | awk '{print $1}'"
    register: expected_checksum
    tags:
      - neovim-latest

  - name: Compute the actual neovim checksum of the downloaded file
    shell: "sha256sum {{ temp_dir }}/nvim.appimage | awk '{print $1}'"
    register: actual_checksum
    tags:
      - neovim-latest

  - name: Verify the neovim checksums match
    fail:
      msg: "Checksum mismatch! Downloaded neovim file may be corrupted."
    when: expected_checksum.stdout not in actual_checksum.stdout
    tags:
      - neovim-latest

  - name: Success message if neovim checksums match
    debug:
      msg: "Neovim checksum verification successful!"
    when: expected_checksum.stdout in actual_checksum.stdout
    tags:
      - neovim-latest

  - name: Copy imagefile to /usr/local/bin/
    ansible.builtin.copy:
      src: "{{ temp_dir }}/nvim.appimage"
      dest: /usr/local/bin/nvim
      mode: '0755'
    become: true
    tags:
      - neovim-latest

  - name: Remove neovim image file
    ansible.builtin.file:
      path: "{{ temp_dir }}/nvim.appimage"
      state: absent
    tags:
      - neovim-latest

  - name: Remove neovim checksum file
    ansible.builtin.file:
      path: "{{ temp_dir }}/nvim.appimage.sha256sum"
      state: absent
    tags:
      - neovim-latest

  tags:
    - install
    - neovim
