- block:
  - name: Install nodejs and npm
    become: true
    apt:
      name: ["nodejs", "npm"]

  - name: Install N
    become: true
    npm:
      name: n
      global: yes

  - name: Install correct version of Node
    become: true
    shell: n 20

  - name: Create new npm global folder
    ansible.builtin.file:
      path: "{{ home_dir }}/.npm-global"
      state: directory
      mode: '0755'

  - name: Set npm global folder config
    shell: "npm config set prefix '{{ home_dir }}/.npm-global'"

  tags:
    - install
    - node
