- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  become: true
  shell: n 20
  tags:
    - install
    - node

- name: Create new npm global folder
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.npm-global"
    state: directory
    mode: '0755'
  tags:
    - install
    - node

- name: Set npm global folder config
  shell: "npm config set prefix '{{ lookup('env', 'HOME') }}/.npm-global'"
  tags:
    - install
    - node
