- block:
  - name: Include variables
    include_vars: auth_codes/variables.yaml

  - name: Cloning personal .dotfiles
    ansible.builtin.git:
      repo: 'git@github.com:coldb/.dotfiles-personal.git'
      dest: "{{ home_dir }}/personal/.dotfiles-personal"
      update: true

  - name: Set personal .dotfiles user.name local configuration
    community.general.git_config:
      name: user.name
      repo: "{{ home_dir }}/personal/.dotfiles-personal"
      scope: local
      value: "{{ git_user }}"

  - name: Set personal .dotfiles user.email local configuration
    community.general.git_config:
      name: user.email
      repo: "{{ home_dir }}/personal/.dotfiles-personal"
      scope: local
      value: "{{ git_email }}"

  - name: Cloning personal ansible
    ansible.builtin.git:
      repo: 'git@github.com:coldb/ansible-personal.git'
      dest: "{{ home_dir }}/personal/ansible-personal"
      update: true

  - name: Set personal ansible user.name local configuration
    community.general.git_config:
      name: user.name
      repo: "{{ home_dir }}/personal/ansible-personal"
      scope: local
      value: "{{ git_user }}"

  - name: Set personal ansible user.email local configuration
    community.general.git_config:
      name: user.email
      repo: "{{ home_dir }}/personal/ansible-personal"
      scope: local
      value: "{{ git_email }}"

  tags:
    - personal
