- name: Install productivity packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "gimp", "xclip", "tldr", "ripgrep", "ksnip" ]
  tags:
    - install
    - productivity
    - testing

- name: Cloning Tmux Plugin Manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git' 
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - productivity

- name: Cloning Tmux Plugin Tmuxifier
  ansible.builtin.git:
    repo: 'https://github.com/jimeh/tmuxifier.git'
    dest: "{{ lookup('env', 'HOME') }}/.tmuxifier"
  tags:
    - install
    - productivity

- name: Get latest Lazygit version from GitHub API
  shell: "curl -s 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest' | grep -Po '\"tag_name\": \"v\\K[^\"]*'"
  register: lazygit_version
  tags:
    - install
    - productivity
    - git

- name: Download latest Lazy Git
  ansible.builtin.get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
    dest: ~/lazygit.tar.gz
  tags:
    - install
    - productivity
    - git

- name: Extract Lazygit tar.gz
  shell: "tar xf ~/lazygit.tar.gz -C ~/"
  tags:
    - install
    - productivity
    - git

- name: Install Lazygit
  shell: "install {{ lookup('env','HOME') }}/lazygit /usr/local/bin"
  become: true
  tags:
    - install
    - productivity
    - git

- name: Remove Lazy Git zip file
  ansible.builtin.file:
    path: ~/lazygit.tar.gz
    state: absent
  tags:
    - install
    - productivity
    - git

- name: Remove Lazy Git unzipped file
  ansible.builtin.file:
    path: ~/lazygit
    state: absent
  tags:
    - install
    - productivity
    - git

- name: Download Slack deb file
  shell: page=$(curl -sL "https://slack.com/downloads/instructions/linux?ddl=1&build=deb") && download_url=$(echo "$page" | grep -oP '(?<=href=")[^"]*slack-desktop-[^"]*.deb') && curl -L "$download_url" -o ~/slack_install.deb
  tags:
    - install
    - productivity

- name: Install Slack
  ansible.builtin.apt:
    deb: "{{ lookup('env','HOME') }}/slack_install.deb"
  become: true
  tags:
    - install
    - productivity

- name: Remove Slack install file
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/slack_install.deb"
    state: absent
  tags:
    - install
    - productivity
