- block:
  - name: Install unzip
    become: true
    apt:
      name: [ "unzip"]
    tags:
      - fonts

  - name: Install productivity packages
    become: true
    apt:
      name: [ "tmux", "wireshark", "fzf", "gimp", "xclip", "tldr", "ripgrep", "ksnip" , "bat", "curl", "htop", "lsof", "gettext"]

  - name: Cloning Tmux Plugin Manager
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/tpm.git' 
      dest: "{{ home_dir }}/.tmux/plugins/tpm"

  - name: Cloning Tmux Plugin Tmuxifier
    ansible.builtin.git:
      repo: 'https://github.com/jimeh/tmuxifier.git'
      dest: "{{ home_dir }}/.tmuxifier"

  - name: Get the latest lazygit version from GitHub
    get_latest_git_release:
      repo_slug: "jesseduffield/lazygit"
    register: lazygit
    tags:
      - lazygit

  - name: Download latest Lazy Git
    ansible.builtin.get_url:
      url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit.latest_version }}_Linux_x86_64.tar.gz"
      dest: "{{ temp_dir }}/lazygit.tar.gz"
    tags:
      - lazygit

  - name: Extract Lazygit tar.gz
    shell: "tar xf {{ temp_dir }}/lazygit.tar.gz -C {{ temp_dir }}"
    tags:
      - lazygit

  - name: Install Lazygit
    shell: "install {{ temp_dir }}/lazygit /usr/local/bin"
    become: true
    tags:
      - lazygit

  - name: Remove Lazy Git zip file
    ansible.builtin.file:
      path: "{{ temp_dir }}/lazygit.tar.gz"
      state: absent
    tags:
      - lazygit

  - name: Remove Lazy Git unzipped file
    ansible.builtin.file:
      path: "{{ temp_dir }}/lazygit"
      state: absent
    tags:
      - lazygit

  - name: Download Slack deb file
    shell: "page=$(curl -sL \"https://slack.com/downloads/instructions/linux?ddl=1&build=deb\") && download_url=$(echo \"$page\" | grep -oP '(?<=href=\")[^\"]*slack-desktop-[^\"]*.deb') && curl -L \"$download_url\" -o {{ temp_dir }}/slack_install.deb"
    tags:
      - slack

  - name: Install Slack
    ansible.builtin.apt:
      deb: "{{ temp_dir }}/slack_install.deb"
    become: true
    tags:
      - slack

  - name: Remove Slack install file
    ansible.builtin.file:
      path: "{{ temp_dir }}/slack_install.deb"
      state: absent
    tags:
      - slack

  - name: Get the latest Bruno version from GitHub
    get_latest_git_release:
      repo_slug: "usebruno/bruno"
    register: bruno
    tags:
      - bruno


  - name: Download latest Bruno executable
    ansible.builtin.get_url:
      url: "https://github.com/usebruno/bruno/releases/download/v{{ bruno.latest_version }}/bruno_{{ bruno.latest_version }}_amd64_linux.deb"
      dest: "{{ temp_dir }}/bruno.deb"
    tags:
      - bruno

  - name: Install Bruno
    ansible.builtin.apt:
      deb: "{{ temp_dir }}/bruno.deb"
    become: true
    tags:
      - bruno

  - name: Remove Bruno install file
    ansible.builtin.file:
      path: "{{ temp_dir }}/bruno.deb"
      state: absent
    tags:
      - bruno

  tags:
    - install
    - productivity
