- block:
  - name: Gather Ubuntu codename
    command: lsb_release -cs
    register: ubuntu_codename
    changed_when: false

  - name: Gather Ubuntu version number
    command: lsb_release -rs
    register: ubuntu_version
    changed_when: false

  - name: Gather architecture
    command: dpkg --print-architecture
    register: ubuntu_architecture
    changed_when: false

  - name: Get current username
    command: id -un
    register: current_username

  - name: Set global facts
    set_fact:
      ubuntu_codename: "{{ ubuntu_codename.stdout }}"
      ubuntu_version: "{{ ubuntu_version.stdout }}"
      ubuntu_architecture: "{{ ubuntu_architecture.stdout }}"
      username: "{{ current_username.stdout }}"
      home_dir: "{{ lookup('env', 'HOME') }}"
      temp_dir: "{{ lookup('env', 'HOME') }}/temp"
      application_dir: "{{ lookup('env', 'HOME') }}/applications"
      personal_dir: "{{ lookup('env', 'HOME') }}/personal"
      work_dir: "{{ lookup('env', 'HOME') }}/work"
      docker_container: "{{ lookup('ansible.builtin.env', 'DOCKER_CONTAINER', default='false') }}"
      dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"

  - name: Create temporary download directory
    file:
      path: "{{ temp_dir }}"
      state: directory
      mode: '0755'

  - name: Create application directory
    file:
      path: "{{ application_dir }}"
      state: directory
      mode: '0755'

  - name: Add universe repository
    become: true
    apt_repository:
      repo: "deb http://archive.ubuntu.com/ubuntu {{ ubuntu_codename }} universe"
      state: present

  - name: Update apt cache
    become: true
    apt:
      update_cache: yes

  - name: Display all facts
    debug:
      msg: 
      - "ubuntu_codename: {{ ubuntu_codename }}"
      - "ubuntu_version: {{ ubuntu_version }}"
      - "ubuntu_architecture: {{ ubuntu_architecture }}"
      - "temp_dir: {{ temp_dir }}"
      - "home_dir: {{ home_dir }}"
      - "personal_dir: {{ personal_dir }}"
      - "work_dir: {{ work_dir }}"
      - "username: {{ username }}"
      - "docker_container: {{ docker_container }}"

  tags:
    - always
