- block:
  - name: Gather Ubuntu codename
    command: lsb_release -cs
    register: ubuntu_codename
    changed_when: false

  - name: Gather architecture
    command: dpkg --print-architecture
    register: ubuntu_architecture
    changed_when: false

  - name: Get current username
    command: id -un
    register: current_username

  - name: Set global facts
    set_fact:
      ubuntu_codename: "{{ ubuntu_codename.stdout }}"
      ubuntu_architecture: "{{ ubuntu_architecture.stdout }}"
      username: "{{ current_username.stdout }}"
      home_dir: "{{ lookup('env', 'HOME') }}"
      temp_dir: "{{ lookup('env', 'HOME') }}/temp"

  - name: Create temporary download directory
    file:
      path: "{{ temp_dir }}"
      state: directory
      mode: '0755'

  - name: Display all facts
    debug:
      msg: 
      - "ubuntu_codename: {{ ubuntu_codename }}"
      - "ubuntu_architecture: {{ ubuntu_architecture }}"
      - "temp_dir: {{ temp_dir }}"
      - "home_dir: {{ home_dir }}"
      - "username: {{ username }}"
  tags:
    - always
