- block:
  - name: Install Window manager (i3)
    become: true
    apt:
      name: "i3"

  - name: Install picom i3 compositor
    become: true
    apt:
      name: "picom"
    tags:
      - install
      - core

  - name: Install polybar for i3
    become: true
    apt:
      name: "polybar"
    tags:
      - install
      - core

  - name: Install rofi to replace dmenu in i3
    become: true
    apt:
      name: "rofi"
    tags:
      - install
      - core

  - name: Install feh for backgrounds in i3
    become: true
    apt:
      name: "feh"
    tags:
      - install
      - core

  - name: Install arandr
    become: true
    apt:
      name: "arandr"
    tags:
      - install
      - core

  tags:
    - i3wm
