- block:
  - name: Include variables
    include_vars: auth_codes/variables.yaml

  - name: Cloning work .dotfiles
    ansible.builtin.git:
      repo: 'git@github.com:coldb/.dotfiles-work.git'
      dest: "{{ home_dir }}/work/.dotfiles-work"
      update: true

  - name: Set work .dotfiles user.name local configuration
    community.general.git_config:
      name: user.name
      repo: "{{ home_dir }}/work/.dotfiles-work"
      scope: local
      value: "{{ git_user }}"

  - name: Set work .dotfiles user.email local configuration
    community.general.git_config:
      name: user.email
      repo: "{{ home_dir }}/work/.dotfiles-work"
      scope: local
      value: "{{ git_email }}"

  - name: Cloning work ansible
    ansible.builtin.git:
      repo: 'git@github.com:coldb/ansible-work.git'
      dest: "{{ home_dir }}/work/ansible-work"
      update: true

  - name: Set work ansible user.name local configuration
    community.general.git_config:
      name: user.name
      repo: "{{ home_dir }}/work/ansible-work"
      scope: local
      value: "{{ git_user }}"

  - name: Set work ansible user.email local configuration
    community.general.git_config:
      name: user.email
      repo: "{{ home_dir }}/work/ansible-work"
      scope: local
      value: "{{ git_email }}"

  tags:
    - work
