- name: Install zsh
  apt: name=zsh
  become: true
  tags:
    - install
    - zsh

- name: Change shell
  shell: chsh -s `which zsh`
  become: true
  tags:
    - install
    - zsh

- name: Check that the .oh-my-zsh exists
  stat:
    path: /home/coldb/.oh-my-zsh
  register: oh_my_stats
  tags:
    - install
    - zsh

- name: Install ohmyzsh
  shell: echo $HOME && curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  tags:
    - install
    - zsh

# Prevent conflic with stowed config
- name: Remove .zshrc configuration
  ansible.builtin.file:
    path: ~/.zshrc
    state: absent
  tags:
  - install
  - zsh

- name: Install the zsh plugin autosuggestiongs
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - zsh
