- name: Upgrade Brave to the latest version
  apt:
    name: brave-browser
    state: latest
  become: true
  tags:
    - update
    - update-brave
    - update-browsers

- block:
  - name: Check if Brave is installed via snap
    command: snap list brave
    register: brave_snap_check
    ignore_errors: true

  - name: Remove Brave if installed via snap
    command: snap remove brave
    when: brave_snap_check.rc == 0
    become: true

  - name: Download Brave browser's GPG key
    ansible.builtin.get_url:
      url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
      dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
    become: true

  - name: Check if Brave browsers repository has been added
    lineinfile:
      path: "/etc/apt/sources.list.d/brave-browser-release.list"
      line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
      create: yes
    become: true

  - name: Update APT package lists
    apt:
      update_cache: yes
    become: true

  - name: Install Brave Browser
    apt:
      name: brave-browser
      state: present
    become: true

  tags:
    - install
    - install-brave
    - install-browsers
