- block:
  - name: Install Firefox
    become: true
    package:
      name: "firefox"

  tags:
    - install
    - install-firefox
    - install-browsers
    - update
    - update-firefox
    - update-browsers
