- name: Install Ghostty block
  block:
  - name: Install ghostty
    become: true
    package:
      name: ghostty

  - name: Clean up the existing Ghostty directory
    ansible.builtin.file:
      path: "{{ home_dir }}/.config/ghostty"
      state: "absent"
    become: true

  - name: Setup the ghostty dotfiles
    command: "./arch"
    args:
      chdir: "{{ dotfiles_dir }}"
    environment:
      STOW_FOLDERS: "ghostty"

  tags:
    - install
    - install-ghostty
    - update
    - update-ghostty
