- block:
  - name: Install NVM (Node Version Manager)
    package:
      name: "nvm"
    become: true

  # - name: Install different node versions
  #   shell: "source /usr/share/nvm/init-nvm.sh"

  - name: Install different node versions
    shell: "source /usr/share/nvm/init-nvm.sh && nvm install 22.16.0"

  tags:
    - install
    - install-node
