- block:
  - name: Install NVM (Node Version Manager)
    package:
      name: "nvm"
    become: true

  - name: Install node versions
    shell: "source /usr/share/nvm/init-nvm.sh && nvm install {{ item }}"
    with_items:
      - "22.16.0"

  tags:
    - install
    - install-node
