- block:
  - name: Install waybar
    become: true
    package:
      name: "waybar"

  - name: Add user to input group
    shell: "usermod -aG input {{ username }}"
    become: true

  - name: Setup the Waybar dotfiles
    command: "./arch"
    args:
      chdir: "{{ dotfiles_dir }}"
    environment:
      STOW_FOLDERS: "waybar"

  tags:
    - install
    - install-waybar
    - update
    - update-waybar

