- block:
  - name: Download latest Cursor ubuntu executable
    ansible.builtin.get_url:
      url: "https://downloads.cursor.com/production/9675251a06b1314d50ff34b0cbe5109b78f848cd/linux/x64/deb/amd64/deb/cursor_1.7.52_amd64.deb"
      dest: "{{ temp_dir }}/cursor.deb"

  - name: Install Cursor
    ansible.builtin.apt:
      deb: "{{ temp_dir }}/cursor.deb"
    become: true

  - name: Remove Cursor install file
    ansible.builtin.file:
      path: "{{ temp_dir }}/cursor.deb"
      state: absent

  tags:
    - install-cursor
    - update-cursor
