- block:
  - name: Get application version from URL
    ansible.builtin.uri:
      url: https://dl.k8s.io/release/stable.txt
      return_content: yes
    register: kubectl_latest_version

  - name: Download latest kubectl
    get_url:
      url: "https://dl.k8s.io/release/{{ kubectl_latest_version.content | trim }}/bin/linux/amd64/kubectl"
      dest: "{{ user_bin }}/kubectl"
      mode: '0755'
      force: true
    become: true

  tags:
    - install
    - install-kubectl
    - update
    - update-kubectl

