- block:
  - name: Install nodejs and npm
    become: true
    apt:
      name: ["nodejs", "npm"]

  - name: Create new npm global folder
    ansible.builtin.file:
      path: "{{ home_dir }}/.npm-global"
      state: directory
      mode: '0755'

  - name: Set npm global folder config
    shell: "npm config set prefix '{{ home_dir }}/.npm-global'"

  - name: Install N
    become: true
    npm:
      name: n
      global: yes

  - name: Install correct version of Node
    become: true
    shell: n 22

  - name: Install Core packages
    npm:
      name: "{{ item }}"
      global: true
    with_items:
      - "yarn"
      - "yalc"
      - "typescript"
      - "ts-node"
      - "swagger-ui-watcher"
      - "vitest"
    tags:
      - install-npm-packages
      - update-npm-packages

  tags:
    - install
    - install-node
