- block:
  - name: Download Microsoft GPG Key
    get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: "{{ temp_dir }}/microsoft.asc"
      mode: '0644'

  - name: Convert GPG Key to dearmored format
    command: gpg --dearmor --output "{{ temp_dir }}/packages.microsoft.gpg" "{{ temp_dir }}/microsoft.asc"
    args:
      creates: "{{ temp_dir }}/packages.microsoft.gpg"

  - name: Move GPG Key to system keyrings
    copy:
      src: "{{ temp_dir }}/packages.microsoft.gpg"
      dest: /etc/apt/keyrings/packages.microsoft.gpg
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Add VS Code Repository
    lineinfile:
      path: /etc/apt/sources.list.d/vscode.list
      line: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
      create: yes
    become: true

  - name: Remove temporary GPG key files
    file:
      path: "{{ temp_dir }}/{{ item }}"
      state: absent
    loop:
      - microsoft.asc
      - packages.microsoft.gpg

  - name: Install Visual Studio Code
    apt:
      name: code
      update_cache: yes
    become: true
    tags:
      - update-vscode

  tags:
    - install-vscode
