- block:
  - name: Install xRDP
    become: true
    apt:
      name: [ "xrdp" ]

  - name: Enable xRDP service and start it
    ansible.builtin.systemd_service:
      name: xrdp
      state: started
      enabled: true
    become: true

  - name: Check if i3 is installed
    command: which i3
    register: i3check_result
    ignore_errors: true
    failed_when: i3check_result.rc != 0 and i3check_result.rc != 1

  - name: Configure xRDP to start i3 session
    shell: "echo 'exec i3' > {{ home_dir }}/.xsession"

  tags:
    - install-xrdp
    - update-xrdp
