- block:
  - name: Get the latest yq version from GitHub
    get_latest_git_release:
      repo_slug: "mikefarah/yq"
    register: yq

  - name: Download latest yq
    get_url:
      url: "https://github.com/mikefarah/yq/releases/download/v{{ yq.latest_version }}/yq_linux_amd64"
      dest: "{{ user_bin }}/yq"
      mode: '0755'
      force: true
    become: true

  tags:
    - install
    - install-yq
    - update
    - update-yq

