- block:
  - name: Install bluetooth tools 
    become: true
    package:
      name: "{{ item }}"
    with_items:
      - "polkit"
      - "bluez"
      - "bluez-utils"

  - name: Enable the bluetooth service
    ansible.builtin.systemd_service:
      name: bluetooth.service
      state: started
      enabled: true
    become: true
    when: docker_container == False

  tags:
    - install
    - install-bluetooth
    - update
    - update-bluetooth
