- block:
  - name: Get current username
    command: id -un
    register: current_username

  - name: Set global facts
    set_fact:
      distribution: "{{ ansible_distribution }}"
      username: "{{ current_username.stdout }}"
      home_dir: "{{ lookup('env', 'HOME') }}"
      temp_dir: "{{ lookup('env', 'HOME') }}/temp"
      application_dir: "{{ lookup('env', 'HOME') }}/applications"
      personal_dir: "{{ lookup('env', 'HOME') }}/personal"
      work_dir: "{{ lookup('env', 'HOME') }}/work"
      docker_container: "{{ lookup('ansible.builtin.env', 'DOCKER_CONTAINER', default='false') }}"
      dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"
      user_bin: "/usr/local/bin"

  - name: Create temporary download directory
    file:
      path: "{{ temp_dir }}"
      state: directory
      mode: '0755'

  - name: Create application directory
    file:
      path: "{{ application_dir }}"
      state: directory
      mode: '0755'

  - name: Display all facts
    debug:
      msg: 
      - "distribution: {{ distribution }}"
      - "username: {{ username }}"
      - "home_dir: {{ home_dir }}"
      - "temp_dir: {{ temp_dir }}"
      - "dotfiles_dir: {{ dotfiles_dir }}"
      - "application_dir: {{ application_dir }}"
      - "personal_dir: {{ personal_dir }}"
      - "work_dir: {{ work_dir }}"
      - "user_bin: {{ user_bin }}"
      - "docker_container: {{ docker_container }}"

  - name: Check if yay is installed
    ansible.builtin.command: "which yay"
    register: yay_check
    changed_when: false
    failed_when: false # Don't fail if yay is not found, we'll install it

  - name: Install yay (AUR Helper) if not present
    when: yay_check.rc != 0
    block:
      - name: Clone yay repository
        ansible.builtin.git:
          repo: "https://aur.archlinux.org/yay.git"
          dest: "{{ temp_dir }}/yay"
          clone: yes
          update: no # We just need to clone it once to build
        become: no # Explicitly run this task without sudo

      - name: Build and install yay
        ansible.builtin.command: "makepkg -si --noconfirm"
        args:
          chdir: "{{ temp_dir }}/yay"
        become: no # Explicitly run this task without sudo

      - name: Clean up yay build directory
        ansible.builtin.file:
          path: "{{ temp_dir }}/yay"
          state: absent
        become: no # No sudo needed to remove a temp dir owned by the user  tags

  tags:
    - always
