# TODO: Cleanup
# - import_tasks: appimage.yaml
# - import_tasks: flatpak.yaml

- name: Installing stow
  package:
    name: "stow"
  become: true
  tags:
    - always

- block:
  - name: Install basic tools
    become: true
    package:
      name: "{{ item }}"
    with_items:
      - "base-devel" # software building tools
      - "go" # go compiler and dev tools
      - "rust" # rust compiler and cargo
      - "composer" # dependency manager for PHP
      - "jdk-openjdk" # Java JDK
      - "luarocks" # Lua package manager
      - "ruby" # Lua package manager
      - "julia" # Julia programming language
      - "python-pip" # Python package manager
      - "htop"
      - "btop"
      - "openssh"
      - "unzip"
      - "wget"
      - "bat" # pretty print file content
      - "ksnip" # screenshot capturing
      - "tldr" # community maintained cheatsheets for command line commands
      - "ripgrep" # faster greping
      - "lsof" # List open files
      - "jq" # JSON navigation
      - "yq" # Yaml navigation
      - "direnv"
      - "arch-audit"
      - "wl-clipboard" # Clipboard support for wayland
      - "hypridle"
      - "hyprlock"
      - "sops"
      - "age"

  - name: Install Basic tools from AUR
    kewlfft.aur.aur:
      name: "{{ item }}"
      state: present
      use: yay
    with_items:
      - "balena-etcher"

  tags:
    - install
    - update
