- block:
  - name: Install Core packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "build-essential"
      - "cmake"
      - "pkg-config"
      - "libpthread-stubs0-dev"
      - "python3-pip"
      - "dconf-editor"
      - "moreutils"
      - "lua5.1"

  - name: Install productivity packages
    become: true
    apt:
      name: "{{ item }}"
    with_items:
      - "unzip"
      - "wireshark"
      - "fzf"
      - "gimp"
      - "xclip"
      - "tldr"
      - "ripgrep"
      - "ksnip"
      - "bat"
      - "curl"
      - "htop"
      - "lsof"
      - "gettext"
      - "jq"
      - "direnv"
      - "ondir"

  - name: Check for backlight directory
    stat:
      path: /sys/class/backlight
    register: backlight_path

  - name: Check if backlight control exists
    command: ls /sys/class/backlight
    when: backlight_path.stat.exists
    register: backlight_dirs
    ignore_errors: true

  - name: Install brightnessctl
    apt:
      name: ["brightnessctl"]
    become: true
    when: docker_container == False and backlight_dirs.stdout != ""

  tags:
    - install
    - install-core
    - update
    - update-core
