- block:
  - name: Check if zsh is installed
    is_program_installed:
      name: zsh
    register: zsh_check

  - name: Install zsh
    become: true
    package:
      name: zsh
    tags:
      - update
      - update-zsh

  - name: Find the path of zsh
    shell: which zsh
    register: zsh_path
    changed_when: False

  - name: Change shell
    become: true
    user:
      name: "{{ username }}"
      shell: "{{ zsh_path.stdout.strip() }}"
    when: not zsh_check.exists

  - name: Check that the .oh-my-zsh exists
    stat:
      path: "{{ home_dir }}/.oh-my-zsh"
    register: oh_my_stats

  - name: Install ohmyzsh
    shell: "echo $HOME && curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > {{ temp_dir }}/.oh-my-installer && chmod +x {{ temp_dir }}/.oh-my-installer && {{ temp_dir }}/.oh-my-installer"
    when: oh_my_stats.stat.exists == False

  - name: Remove .zshrc configuration
    ansible.builtin.file:
      path: "{{ home_dir }}/.zshrc"
      state: absent
    when: not zsh_check.exists

  - name: Install the zsh plugin autosuggestiongs
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: "{{ home_dir }}/.oh-my-zsh/plugins/zsh-autosuggestions"

  - name: Setup the zsh dotfiles
    command: "./arch"
    args:
      chdir: "{{ dotfiles_dir }}"
    environment:
      STOW_FOLDERS: "zsh"

  tags:
    - install
    - install-zsh
